src/components/Footer/index.tsx, src/components/ImageCarousel/index.tsx, src/pages/Home/HomeTopic/index.tsx, src/pages/Home/HomeTopic/styles.ts
This pull request adds a WhatsApp link to the Footer component, allowing users to easily contact the project team. It also includes some minor code improvements and fixes.
=> Add WhatsApp link to Footer component

src/pages/Home/HomeTopic/texts/styles.ts
This pull request adds a hover effect to the DataTitle component in order to improve user experience.
=> Add hover effect to DataTitle component

src/App.tsx, src/components/Footer/styles.ts, src/components/Header/index.tsx, src/components/Header/styles.ts, src/components/HomeSearch/styles.ts, src/components/ImageCarousel/styles.ts, src/components/ImageCarousel2/styles.ts, src/pages/Home/HomeTopic/styles.ts, src/pages/Home/HomeTopic/texts/styles.ts, src/pages/Home/index.tsx, src/pages/Home/styles.ts, src/pages/SearchPage/index.tsx, src/pages/SearchPage/styles.ts, src/utils/colors.ts, src/utils/strings.ts, tsconfig.json
This pull request includes updates to the styles in ImageCarousel2, Home, and other pages, as well as updates to the routes and navigation in App.tsx and Header component. It also adds a new alias for the src folder in vite.config.js and updates the header buttons.
=> Update styles and routes in App.tsx, Header component, and other files

src/components/Footer/index.tsx, src/components/Footer/social-media.css, src/components/Footer/styles.ts, src/components/Header/styles.ts, src/components/ImageCarousel/styles.ts, src/components/ImageCarousel2/styles.ts, src/components/Item/texts/styles.ts, src/components/SearchBar/styles.ts, src/index.css, src/pages/Home/RoundBox/styles.ts, src/pages/Home/styles.ts, src/pages/SearchPage/index.tsx, src/pages/SearchPage/styles.ts
This pull request includes updates to the CSS files to improve responsiveness. It adjusts font sizes, padding, spacing, and margins in various components to ensure a better user experience on different devices and screen sizes.
=> Update styles for responsiveness

src/pages/Home/index.tsx
This pull request comments out the ImageCarousel component in the Home page to temporarily remove it from the UI.
=> Comment out ImageCarousel component in Home page

declarations.d.ts, package-lock.json, package.json, src/components/Header/index.tsx, src/components/ImageCarousel2/index.tsx, src/components/SearchBar/index.tsx, src/components/SearchBar/styles.ts, src/index.css, src/pages/Home/HomeTopic/index.tsx, src/pages/Home/index.tsx, src/pages/SearchPage/TopicSearch/index.tsx, src/pages/SearchPage/churchMap/index.tsx, src/pages/SearchPage/churchMap/styles.ts, src/pages/SearchPage/index.tsx, src/utils/mockData.ts, src/utils/strings.ts
Refactor SearchPage to include ChurchMap component
Remove unused CSS styles in index.css
Add sigla markers on hover in ChurchMap component
Update CSS styles in index.css and add state name markers on hover in ChurchMap component
Update button labels and paths in Header component
Fix file paths and import statements in SearchPage and ChurchMap components
Fix button logic and update margin in SearchBar component
Update header component and add topic search functionality
Update CSS styles in index.css and add state name markers on hover in ChurchMap component
Update autoplay speed in ImageCarousel2 component
=> Update button labels in Header and SearchBar components

src/components/Tags/index.tsx
This pull request adds click functionality to the Tag component in the Tags/index.tsx file. Now, when a tag is clicked, it will navigate to the corresponding topic page. This improves the user experience by allowing them to easily explore topics of interest.
=> Add click functionality to Tag component in Tags/index.tsx

src/App.tsx, src/components/Header/index.tsx, src/pages/about/index.tsx, src/pages/about/styles.ts
- Added AboutPage component to display information about the project
- Updated Header navigation to include a link to the AboutPage
=> feat: Add AboutPage component and update Header navigation

queries.txt, src/components/TextTruncate/index.tsx, src/components/TextTruncate/styles.ts, src/pages/ChurchState/index.tsx, src/pages/ItemDetails/index2.tsx, src/pages/ItemDetails/styles.ts, src/pages/SearchPage/ChurchMap/index.tsx, tsconfig.json
This pull request adds a new component called TextTruncate that allows for truncating text with a character limit and displaying ellipsis. It also includes a hover effect that reveals the full text on mouse hover. The component has been styled and implemented with FontAwesome icons for dynamic sizing. Additionally, improvements have been made to the truncation and styling in the TextTruncate component.
=> "Add TextTruncate component with truncation and hover effect"

src/components/Item/index.tsx, src/components/Item/texts/styles.ts, src/components/Tags/index.tsx, src/pages/SearchPage/styles.ts, src/pages/TagDetail/index.tsx, src/pages/TagDetail/styles.ts
- Modify Item component in src/components/Item/index.tsx to accept width and tagCount props
- Update usage of Item component in src/pages/TagDetail/index.tsx to pass width and tagCount props
=> feat: Add width and tagCount props to Item component

src/assistant.tsx, src/components/DataTable/index.tsx, src/components/DataTable/styles.css, src/components/DataTable/styles.ts, src/pages/Dashboard/index.tsx, src/pages/Dashboard/styles.ts, src/utils/mockData.ts
Refactor the DataTable component to update the valueGetter and valueFormatter functions. This change ensures consistency and improves the readability of the code. Additionally, the component now supports lazy loading for images.
=> Refactor DataTable component

src/App.tsx
This pull request adds styling to the button component, giving it a white background with 90% opacity and a border radius of 1.6rem. This improves the visual appearance of the button.
=> Add button styling

src/App.tsx, src/api/chatBot.ts, src/api/chatbot.ts, src/assistant.tsx, src/components/Header/index.tsx, src/index.css, src/pages/About/styles.ts, src/pages/Details/ChurchDetail/index.tsx, src/pages/Details/PaintingDetail/index.tsx, src/pages/Details/styles.ts, src/pages/TagDetail/index.tsx, src/pages/TagDetail/styles.ts
This pull request includes refactoring the makeOpenAIRequest function to handle different types of items and includes additional information for paintings and churches. It also updates the image max-height in the Details page and adds a mobile warning message.
=> Refactor makeOpenAIRequest function and update image styling in Details page

CNAME, src/api/chatbot.ts, src/assistant.tsx, src/components/Header/index.tsx, src/components/OptionButton/index.tsx, src/components/OptionButton/styles.ts, src/pages/Dashboard/index.tsx, src/pages/Dashboard/styles.ts, src/pages/LoginPage/index.tsx, src/pages/SubmitPage/index.tsx
This pull request includes several changes to the SubmitPage component and adds new features to the application. The changes include fixing the dependency array in the useEffect hook, adding required fields, updating error messages, updating API endpoints to use environment variables, and updating the Dashboard component to use lazy loading for images. Additionally, a new feature has been added to allow users to submit new works and check the submission status in the user dashboard.
=> Refactor SubmitPage and add new features

vite.config.js
Updated the deploy config to set the base URL to "/" instead of "/paineis-do-carmo/". This ensures that the application is deployed correctly.
=> Update deploy config

.github/workflows/deploy-preview.yml, src/App.tsx
This pull request updates the build process to include environment variables. Previously, the build process did not include the necessary environment variables, causing issues with the application. This update ensures that the environment variables are available during the build process, improving the reliability and functionality of the application.
=> Update build process to include environment variables

src/context/AuthContext.tsx, src/pages/Dashboard/index.tsx
This pull request includes a refactoring of the AuthContext to use TypeScript and updates the dependencies.
=> Refactor AuthContext to use TypeScript and update dependencies

src/components/Header/index.tsx, src/pages/Dashboard/AdminDash/index.tsx, src/pages/Dashboard/UserDash/index.tsx, src/pages/SubmitPage/index.tsx
This pull request includes several changes to improve the localization of the application. The error messages in the Admin and User Dashboards have been updated to Portuguese for better user understanding. Additionally, the church data fetching has been refactored to set unique churches, ensuring that duplicate churches are not displayed. These changes enhance the user experience by providing localized error messages and improving the accuracy of the displayed church data.
=> Refactor error messages to Portuguese and update church data fetching

src/components/Header/index.tsx
The isLoggedIn function in the Header component is updated to handle the "admin" token separately. Previously, the function only checked if the token existed and was not expired. Now, it also checks if the token is not equal to "admin" before performing the expiration check. This change ensures that the "admin" token is not considered as a valid login and prevents unnecessary expiration alerts for the "admin" user.
=> refactor: Update isLoggedIn function to handle "admin" token

src/pages/Dashboard/AdminDash/index.tsx, src/pages/Dashboard/UserDash/index.tsx, src/pages/Details/ChurchDetail/index.tsx, src/pages/Details/PaintingDetail/index.tsx, src/pages/LoginPage/index.tsx, src/pages/RegisterPage/index.tsx, src/pages/SearchPage/TopicSearch/index.tsx, src/pages/SearchPage/index.tsx, src/pages/SubmitPage/index.tsx
Refactor the TopicSearch component to remove the unused SearchBar with the showButtons prop. In the PaintingDetail component, adjust the height of the loading spinner container to 80vh for better layout. Update the size of the CircularProgress component to 100 for better visibility. Add conditional rendering for the "Gravuras" section to display only if there are engraving data available. Update the alt attribute for EngravingImage and EngravingDescription components to use engraving name or default value. In the ChurchDetail component, add conditional rendering for the "Obras da Igreja" section to display only if there are painting data available. Update the alt attribute for EngravingImage and EngravingDescription components to use painting title or default value. Update the font size …
=> + Refactor TopicSearch component and PaintingDetail/ChurchDetail components

src/pages/SubmitPage/index.tsx
This pull request refactors the error handling in the SubmitPage component. The previous error handling code has been removed and replaced with a more efficient and streamlined approach. This change improves the overall reliability and user experience of the SubmitPage component.
=> Refactor error handling in SubmitPage component

src/components/Item/styles.ts, src/pages/Home/styles.ts, src/pages/SearchPage/index.tsx, src/pages/SubmitPage/index.tsx, src/pages/TagDetail/index.tsx
This pull request includes refactoring changes to the SubmitPage, TagDetail, and SearchPage components. The SubmitPage component has been refactored to clear form inputs and selected images on submission. The TagDetail component has been refactored to center the loading spinner. The SearchPage component has been refactored to handle and display error messages. Additionally, there are some adjustments made to the gaps in the TopicsContainer component.
=> Refactor SubmitPage, TagDetail, and SearchPage components

src/pages/SearchPage/ChurchMap/index.tsx
This pull request refactors the ChurchMap component to add the functionality of displaying the state name on hover. It introduces a new component called ShowStateNameOnHover, which uses the react-leaflet library to handle the map interactions. The component listens for mouse events on the map and updates the state name icon accordingly. Additionally, it includes a navigation feature that redirects the user to a specific page when a state is clicked.
=> Refactor ChurchMap component to add state name on hover

src/pages/SearchPage/index.tsx
Improve search capabilities by allowing filtering of results based on tags in addition to titles.
=> Enhance search functionality to include tags in filtering results

src/components/Footer/index.tsx, src/pages/SearchPage/TopicSearch/index.tsx, src/pages/TagDetail/index.tsx
Update the footer link to direct users to the GitHub repository. Improve search functionality to display "no data" messages when no results are found.
=> Update footer link and enhance search functionality

src/pages/Home/index.tsx
Incorporate video URLs into the RoundBox components to enhance content on the Home page.
=> Add video URLs to RoundBox components on Home page

src/api/chatbot.ts, src/pages/Dashboard/AdminDash/index.tsx, src/pages/RegisterPage/index.tsx, src/pages/SearchPage/ChurchMap/index.tsx, src/pages/SearchPage/index.tsx, src/pages/SubmitPage/index.tsx
Improve handling of bibliography references by ensuring they are properly filtered and formatted. Remove unnecessary console log statements for cleaner code.
=> Refactor bibliography references handling and remove console logs

src/components/DeleteModal/index.tsx, src/pages/Dashboard/AdminDash/index.tsx, src/pages/Details/ChurchDetail/index.tsx, src/pages/Details/PaintingDetail/index.tsx, src/pages/SubmitPage/index.tsx, src/utils/mockData.ts
Enhance consistency in bibliography references handling and update rendering logic across various components for better clarity and functionality.
=> Refactor bibliography references handling and improve rendering logic

src/pages/Dashboard/AdminDash/index.tsx, src/pages/Details/PaintingDetail/index.tsx, src/pages/SubmitPage/index.tsx
Improve optional chaining and streamline bibliography references handling by removing unnecessary console logs.
=> Refactor bibliography source handling in AdminDash and SubmitPage components

src/pages/Dashboard/AdminDash/index.tsx, src/pages/SubmitPage/index.tsx
Improve type safety and consistency in handling bibliography references and sources in the AdminDash and SubmitPage components.
=> Refactor bibliography handling for type safety and consistency

.github/workflows/deploy-preview.yml
Upgrade the GitHub Actions used for configuring, uploading artifacts, and deploying to GitHub Pages to their latest versions for improved performance and features.
=> Update GitHub Actions to latest versions for Pages deployment

src/pages/Details/PaintingDetail/index.tsx, src/pages/SubmitPage/index.tsx, src/utils/mockData.ts
Include creator details for engravings and improve the management of gravuras by allowing for the removal of specific entries without deleting them from the state.
=> Add creator information to engravings and enhance gravura handling in SubmitPage

src/pages/Details/PaintingDetail/index.tsx, src/pages/SubmitPage/index.tsx, src/utils/mockData.ts
Introduce multiple bibliography sources display in PaintingDetails and improve author filtering and textarea styles in SubmitPage. Update Painting interface to support an array of bibliography sources.
=> Enhance PaintingDetails and SubmitPage components with bibliography sources

src/App.tsx, src/components/Footer/index.tsx, src/components/Footer/styles.ts, src/components/Footer/stylesMobile.ts, src/components/Header/index.tsx, src/components/Header/styles.ts, src/components/Header/stylesMobile.ts, src/components/ImageCarousel2/styles.ts, src/index.css, src/pages/Home/HomeTopicMobile/index.tsx, src/pages/Home/HomeTopicMobile/styles.ts, src/pages/Home/index.tsx, src/pages/Home/stylesMobile.ts, src/pages/SubmitPage/index.tsx
Remove mobile restrictions and implement responsive designs for Header, Footer, and Home components. Refactor styles for better organization and readability, ensuring a seamless mobile experience.
=> Enhance mobile responsiveness and layout improvements

src/components/Footer/index.tsx, src/components/Header/styles.ts
Improve the responsiveness of social media links in the Footer and ensure consistent sizing for Header icons by applying max-width styling.
=> Enhance responsiveness of Footer and Header icons

src/components/Footer/index.tsx
Adjust max-width for social media links in the Footer to ensure consistent styling across different platforms.
=> Update max-width styling for social media links in Footer

src/assistant.tsx, src/components/Footer/index.tsx, src/components/Footer/stylesMobile.ts, src/components/Header/index.tsx, src/pages/About/index.tsx, src/pages/About/stylesMobile.ts, src/pages/SearchPage/ChurchMap/index.tsx, src/pages/SearchPage/TopicSearch/index.tsx, src/pages/SearchPage/TopicSearch/styles.ts, src/pages/SearchPage/index.tsx, src/pages/SearchPage/stylesMobile.ts
Improve styling and layout for the Assistant, Footer, SearchPage, and About page, ensuring a better user experience across mobile devices.
=> Refactor components and enhance mobile responsiveness

src/components/Footer/stylesMobile.ts, src/components/Header/index.tsx, src/components/ImageCarousel/index.tsx, src/components/ImageCarousel/styles.ts, src/index.css, src/pages/ChurchState/index.tsx, src/pages/Dashboard/AdminDash/index.tsx, src/pages/Dashboard/AdminDash/styles.ts, src/pages/Dashboard/UserDash/index.tsx, src/pages/Dashboard/UserDash/styles.ts, src/pages/Details/ChurchDetail/index.tsx, src/pages/Details/PaintingDetail/index.tsx, src/pages/Details/stylesMobile.ts, src/pages/SearchPage/ChurchMap/index.tsx, src/pages/SearchPage/index.tsx, src/pages/SearchPage/styles.ts, src/pages/SearchPage/stylesMobile.ts, src/pages/TagDetail/index.tsx
Improve mobile usability by adding responsive styles and layouts to various components, including the footer, church details, search pages, and image carousel. Refactor components for better user experience on mobile devices.
=> Enhance mobile responsiveness across components

src/App.tsx, src/components/Footer/stylesMobile.ts, src/pages/About/index.tsx, src/pages/ChurchState/index.tsx, src/pages/Dashboard/AdminDash/index.tsx, src/pages/Dashboard/UserDash/index.tsx, src/pages/Details/ChurchDetail/index.tsx, src/pages/Details/PaintingDetail/index.tsx, src/pages/Home/index.tsx, src/pages/TagDetail/index.tsx
Update mobile detection logic across multiple components to initialize the `isMobile` state based on the current window width. This change improves responsiveness and ensures accurate mobile detection.
=> Refactor mobile detection initialization

src/utils/mockData.ts
Comment out unused tags in the brazilianPaintings dataset to enhance clarity and provide future reference.
=> Comment out unused tags in brazilianPaintings data

src/components/Footer/index.tsx
Eliminate the WhatsApp link from the footer component to streamline social media options.
=> Remove WhatsApp link from footer

src/components/Modal/index.tsx, src/pages/Details/PaintingDetail/index.tsx, src/pages/SearchPage/TopicSearch/index.tsx, src/pages/SearchPage/TopicSearch/styles.ts
Enhance the Modal component to conditionally lock scroll based on a new prop and integrate modal functionality in the PaintingDetails component. Improve the layout of the TopicSearch component and refine styles for BigTag and BigTagMobile for better consistency and responsiveness.
=> Refactor Modal and TopicSearch components for improved functionality and responsiveness

src/pages/ChurchState/index.tsx, src/pages/Dashboard/AdminDash/index.tsx, src/pages/Details/ChurchDetail/index.tsx
Enhance loading alignment in mobile components and the ChurchState component. Introduce street address display in the PaintingDetails component. Implement sortable headers for paintings and churches in the Dashboard component.
=> Improve loading alignment and add new features

src/pages/SearchPage/TopicSearch/index.tsx, src/pages/SearchPage/index.tsx, src/pages/SearchPage/styles.ts
Introduce sorting functionality in the SearchPage component, enhance styling for the SearchBarContainer, and ensure consistent layout in the TopicSearch component.
=> Refactor SearchPage with sorting and improved layout

src/pages/Details/styles.ts, src/pages/SearchPage/ChurchMap/styles.ts
Enhance the visual presentation of the Container and SearchHeader components by updating styles for better text alignment and spacing.
=> Improve text alignment and spacing in Container and SearchHeader components

src/components/Item/index.tsx, src/pages/Details/stylesMobile.ts
Enhance readability by adding text alignment to ContainerMobile styles and increase the click area by moving the onClick handler to the Data wrapper in the Item component.
=> Improve text alignment and click area in Item component

src/assistant.tsx, src/pages/LoginPage/styles.ts, src/pages/RegisterPage/styles.ts
Enhance the readability of the Assistant, LoginPage, and RegisterPage by adjusting font sizes in their styles.
=> Adjust font sizes for improved readability in Assistant, LoginPage, and RegisterPage

.github/workflows/deploy-preview.yml, package-lock.json, package.json, src/main.jsx, src/pages/LoginPage/index.tsx, src/pages/RegisterPage/index.tsx
Integrate Google OAuth for user authentication in both login and registration pages. Update environment variables and dependencies to support the new feature.
=> Add Google login functionality

src/pages/Dashboard/AdminDash/index.tsx, src/pages/Details/styles.ts
Introduce sorting functionality for church names in the paintings table and enhance the Image component styles for better responsiveness using max-width and max-height.
=> Add sorting for church names and improve image responsiveness

.github/workflows/deploy-preview.yml, src/api/chatbot.ts
Reintroduce public variables for environment configuration and replace the OpenAI API key with a proxy URL in the chatbot API request to enhance security and flexibility.
=> Restore public variables and update API request method
